<?php
/**
 * CMS view template
 *

 */
?>
<?php if (new DateTime() < new DateTime("2017-10-01 00:00:00")): ?>
	<br />
	<h3>September 2017</h3>
	<br />
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2017-09-04 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="cmrcday">04</span>
		<p class="block-title">The Complete Micro-ring Course 4th September 2017 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Sep 04th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Complete Micro-ring course at our Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2017-09-25 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="cmrcday">25</span>
		<p class="block-title">The Complete Micro-ring Course 25th September 2017 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Sep 25th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Complete Micro-ring course at our Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2017-11-01 00:00:00")): ?>
	<br />
	<h3>October 2017</h3>
	<br />
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2017-10-09 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="cmrcday">09</span>
		<p class="block-title">The Complete Micro-ring Course 9th October 2017 London</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Oct 09th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Complete Micro-ring course at our Training Academy in London. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-london.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Chelsea, London, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Real Hair, 6 Cale Street Chelsea" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2017-10-16 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="cmrcday">16</span>
		<p class="block-title">The Complete Micro-ring Course 16th October 2017 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Oct 16th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Complete Micro-ring course at our Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2017-12-01 00:00:00")): ?>
	<br />
	<h3>November 2017</h3>
	<br />
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2017-11-06 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="cmrcday">06</span>
		<p class="block-title">The Complete Micro-ring Course 6th November 2017 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Nov 06th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Complete Micro-ring course at our Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2017-10-20 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="cmrcday">20</span>
		<p class="block-title">The Complete Micro-ring Course 20th November 2017 London</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Nov 20th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Complete Micro-ring course at our Training Academy in London. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-london.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Chelsea, London, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Real Hair, 6 Cale Street Chelsea" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2017-11-27 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="cmrcday">27</span>
		<p class="block-title">The Complete Micro-ring Course 27th November 2017 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Nov 27th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Complete Micro-ring course at our Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2018-01-01 00:00:00")): ?>
	<br />
	<h3>December 2017</h3>
	<br />
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2017-11-18 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="cmrcday">18</span>
		<p class="block-title">The Complete Micro-ring Course 18th December 2017 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Dec 18th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Complete Micro-ring course at our Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2018-02-01 00:00:00")): ?>
	<br />
	<h3>January 2018</h3>
	<br />
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2018-01-08 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="cmrcday">08</span>
		<p class="block-title">The Complete Micro-ring Course 8th January 2018 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Jan 8th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Complete Micro-ring course at our Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2018-01-23 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="cmrcday">23</span>
		<p class="block-title">The Complete Micro-ring Course 23rd January 2018 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Jan 23rd 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Complete Micro-ring course at our Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2018-03-01 00:00:00")): ?>
	<br />
	<h3>February 2018</h3>
	<br />
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2018-02-05 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="cmrcday">05</span>
		<p class="block-title">The Complete Micro-ring Course 5th February 2018 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Feb 5th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Complete Micro-ring course at our Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2018-02-12 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="cmrcday">12</span>
		<p class="block-title">The Complete Micro-ring Course 12th February 2018 London</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Feb 12th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Complete Micro-ring course at our Training Academy in London. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-london.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Chelsea, London, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Real Hair, 6 Cale Street Chelsea" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2018-02-19 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="cmrcday">19</span>
		<p class="block-title">The Complete Micro-ring Course 19th February 2018 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Feb 19th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Complete Micro-ring course at our Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2018-04-01 00:00:00")): ?>
	<br />
	<h3>March 2018</h3>
	<br />
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2018-03-06 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="cmrcday">06</span>
		<p class="block-title">The Complete Micro-ring Course 6th March 2018 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Mar 6th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Complete Micro-ring course at our Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2018-03-20 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="cmrcday">20</span>
		<p class="block-title">The Complete Micro-ring Course 20th March 2018 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Mar 20th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Complete Micro-ring course at our Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2018-05-01 00:00:00")): ?>
	<br />
	<h3>April 2018</h3>
	<br />
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2018-04-03 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="cmrcday">03</span>
		<p class="block-title">The Complete Micro-ring Course 3rd April 2018 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Apr 3rd 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Complete Micro-ring course at our Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2017-04-09 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="cmrcday">09</span>
		<p class="block-title">The Complete Micro-ring Course 9th April 2018 London</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Apr 9th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Complete Micro-ring course at our Training Academy in London. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-london.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Chelsea, London, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Real Hair, 6 Cale Street Chelsea" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2018-04-16 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="cmrcday">16</span>
		<p class="block-title">The Complete Micro-ring Course 16th April 2018 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Apr 16th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Complete Micro-ring course at our Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2018-04-30 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="cmrcday">30</span>
		<p class="block-title">The Complete Micro-ring Course 30th April 2018 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Apr 30th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Complete Micro-ring course at our Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2018-06-01 00:00:00")): ?>
	<br />
	<h3>May 2018</h3>
	<br />
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2018-05-14 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="cmrcday">14</span>
		<p class="block-title">The Complete Micro-ring Course 14th May 2018 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>May 14th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Complete Micro-ring course at our Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2018-05-29 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="cmrcday">29</span>
		<p class="block-title">The Complete Micro-ring Course 29th May 2018 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>May 29th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Complete Micro-ring course at our Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2018-07-01 00:00:00")): ?>
	<br />
	<h3>June 2018</h3>
	<br />
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2018-06-04 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="cmrcday">04</span>
		<p class="block-title">The Complete Micro-ring Course 4th June 2018 London</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Jun 4th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Complete Micro-ring course at our Training Academy in London. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-london.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Chelsea, London, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Real Hair, 6 Cale Street Chelsea" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2018-06-12 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="cmrcday">12</span>
		<p class="block-title">The Complete Micro-ring Course 12th June 2018 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>June 12th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Complete Micro-ring course at our Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2018-06-26 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="cmrcday">26</span>
		<p class="block-title">The Complete Micro-ring Course 26th June 2018 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>June 26th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Complete Micro-ring course at our Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2018-08-01 00:00:00")): ?>
	<br />
	<h3>July 2018</h3>
	<br />
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2018-07-09 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="cmrcday">09</span>
		<p class="block-title">The Complete Micro-ring Course 9th July 2018 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>July 9th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Complete Micro-ring course at our Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2018-07-23 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="cmrcday">23</span>
		<p class="block-title">The Complete Micro-ring Course 23rd July 2018 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>July 23rd 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Complete Micro-ring course at our Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2018-09-01 00:00:00")): ?>
	<br />
	<h3>August 2018</h3>
	<br />
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2018-08-06 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="cmrcday">06</span>
		<p class="block-title">The Complete Micro-ring Course 6th August 2018 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Aug 6th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Complete Micro-ring course at our Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2018-08-06 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="cmrcday">06</span>
		<p class="block-title">The Complete Micro-ring Course 6th August 2018 London</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Aug 6th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Complete Micro-ring course at our Training Academy in London. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-london.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Chelsea, London, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Real Hair, 6 Cale Street Chelsea" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2018-08-20 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="cmrcday">20</span>
		<p class="block-title">The Complete Micro-ring Course 20th August 2018 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Aug 20th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Complete Micro-ring course at our Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>



<?php if (new DateTime() < new DateTime("2018-10-01 00:00:00")): ?>
	<br />
	<h3>September 2018</h3>
	<br />
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2018-09-10 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="cmrcday">10</span>
		<p class="block-title">The Complete Micro-ring Course 10th September 2018 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Sep 10th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Complete Micro-ring course at our Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2018-09-25 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="cmrcday">25</span>
		<p class="block-title">The Complete Micro-ring Course 25th September 2018 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Sep 25th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Complete Micro-ring course at our Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>



<?php if (new DateTime() < new DateTime("2018-11-01 00:00:00")): ?>
	<br />
	<h3>October 2018</h3>
	<br />
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2018-10-08 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="cmrcday">08</span>
		<p class="block-title">The Complete Micro-ring Course 8th October 2018 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Oct 8th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Complete Micro-ring course at our Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2018-10-08 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="cmrcday">08</span>
		<p class="block-title">The Complete Micro-ring Course 8th October 2018 London</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Oct 8th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Complete Micro-ring course at our Training Academy in London. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-london.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Chelsea, London, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Real Hair, 6 Cale Street Chelsea" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2018-10-22 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="cmrcday">22</span>
		<p class="block-title">The Complete Micro-ring Course 22nd October 2018 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Oct 22nd 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Complete Micro-ring course at our Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>



<?php if (new DateTime() < new DateTime("2018-12-01 00:00:00")): ?>
	<br />
	<h3>November 2018</h3>
	<br />
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2018-11-06 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="cmrcday">06</span>
		<p class="block-title">The Complete Micro-ring Course 6th November 2018 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Nov 6th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Complete Micro-ring course at our Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2018-11-19 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="cmrcday">19</span>
		<p class="block-title">The Complete Micro-ring Course 19th November 2018 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Nov 19th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Complete Micro-ring course at our Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2019-01-01 00:00:00")): ?>
	<br />
	<h3>December 2018</h3>
	<br />
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2018-12-04 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="cmrcday">04</span>
		<p class="block-title">The Complete Micro-ring Course 4th December 2018 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Dec 4th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Complete Micro-ring course at our Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2018-12-17 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="cmrcday">17</span>
		<p class="block-title">The Complete Micro-ring Course 17th December 2018 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Dec 17th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Complete Micro-ring course at our Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>



<?php if (new DateTime() < new DateTime("2019-02-01 00:00:00")): ?>
	<br />
	<h3>January 2019</h3>
	<br />
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2019-01-14 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="cmrcday">14</span>
		<p class="block-title">The Complete Micro-ring Course 14th January 2019 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Jan 14th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Complete Micro-ring course at our Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>



<?php if (new DateTime() < new DateTime("2019-03-01 00:00:00")): ?>
	<br />
	<h3>February 2019</h3>
	<br />
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2019-02-05 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="cmrcday">05</span>
		<p class="block-title">The Complete Micro-ring Course 5th February 2019 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Feb 5th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Complete Micro-ring course at our Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2019-02-11 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="cmrcday">11</span>
		<p class="block-title">The Complete Micro-ring Course 11th February 2019 London</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Feb 11th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Complete Micro-ring course at our Training Academy in London. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<div class="uteclocation">
					<p>Location: Marylebone, London, W1H 8AQ, UK</p>
					<a href="http://maps.google.com/maps?f=q&hl=en&&saddr=George%20Street,%20Marylebone,%20London,%20W1H%208AQ" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2019-02-25 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="cmrcday">25</span>
		<p class="block-title">The Complete Micro-ring Course 25th February 2019 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Feb 25th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Complete Micro-ring course at our Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>



<?php if (new DateTime() < new DateTime("2019-04-01 00:00:00")): ?>
	<br />
	<h3>March 2019</h3>
	<br />
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2019-03-18 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="cmrcday">18</span>
		<p class="block-title">The Complete Micro-ring Course 18th March 2019 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Mar 18th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Complete Micro-ring course at our Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2019-05-01 00:00:00")): ?>
	<br />
	<h3>April 2019</h3>
	<br />
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2019-04-08 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="cmrcday">08</span>
		<p class="block-title">The Complete Micro-ring Course 8th April 2019 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Apr 8th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Complete Micro-ring course at our Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2019-04-29 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="cmrcday">29</span>
		<p class="block-title">The Complete Micro-ring Course 29th April 2019 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Apr 29th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Complete Micro-ring course at our Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2019-06-01 00:00:00")): ?>
	<br />
	<h3>May 2019</h3>
	<br />
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2019-05-20 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="cmrcday">20</span>
		<p class="block-title">The Complete Micro-ring Course 20th May 2019 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>May 20th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Complete Micro-ring course at our Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2019-07-01 00:00:00")): ?>
	<br />
	<h3>June 2019</h3>
	<br />
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2019-06-03 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="cmrcday">03</span>
		<p class="block-title">The Complete Micro-ring Course 3rd June 2019 London</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Jun 3rd 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Complete Micro-ring course at our Training Academy in London. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<div class="uteclocation">
					<p>Location: Marylebone, London, W1H 8AQ, UK</p>
					<a href="http://maps.google.com/maps?f=q&hl=en&&saddr=George%20Street,%20Marylebone,%20London,%20W1H%208AQ" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2019-06-10 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="cmrcday">10</span>
		<p class="block-title">The Complete Micro-ring Course 10th June 2019 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>June 10th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Complete Micro-ring course at our Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>



<?php if (new DateTime() < new DateTime("2019-08-01 00:00:00")): ?>
	<br />
	<h3>July 2019</h3>
	<br />
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2019-07-01 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="cmrcday">01</span>
		<p class="block-title">The Complete Micro-ring Course 1st July 2019 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>July 1st 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Complete Micro-ring course at our Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2019-07-22 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="cmrcday">22</span>
		<p class="block-title">The Complete Micro-ring Course 22nd July 2019 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>July 22nd 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Complete Micro-ring course at our Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2019-09-01 00:00:00")): ?>
	<br />
	<h3>August 2019</h3>
	<br />
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2019-08-12 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="cmrcday">12</span>
		<p class="block-title">The Complete Micro-ring Course 12th August 2019 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>August 12th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Complete Micro-ring course at our Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2019-10-01 00:00:00")): ?>
	<br />
	<h3>September 2019</h3>
	<br />
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2019-09-03 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="cmrcday">03</span>
		<p class="block-title">The Complete Micro-ring Course 3rd September 2019 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>September 3rd 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Complete Micro-ring course at our Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2019-09-16 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="cmrcday">16</span>
		<p class="block-title">The Complete Micro-ring Course 16th September 2019 London</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Sep 16th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Complete Micro-ring course at our Training Academy in London. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<div class="uteclocation">
					<p>Location: Marylebone, London, W1H 8AQ, UK</p>
					<a href="http://maps.google.com/maps?f=q&hl=en&&saddr=George%20Street,%20Marylebone,%20London,%20W1H%208AQ" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2019-09-23 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="cmrcday">23</span>
		<p class="block-title">The Complete Micro-ring Course 23rd September 2019 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>September 23rd 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Complete Micro-ring course at our Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2019-11-01 00:00:00")): ?>
	<br />
	<h3>October 2019</h3>
	<br />
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2019-10-14 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="cmrcday">14</span>
		<p class="block-title">The Complete Micro-ring Course 14th October 2019 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>October 14th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Complete Micro-ring course at our Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2019-12-01 00:00:00")): ?>
	<br />
	<h3>November 2019</h3>
	<br />
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2019-11-04 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="cmrcday">04</span>
		<p class="block-title">The Complete Micro-ring Course 4th November 2019 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>November 4th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Complete Micro-ring course at our Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2019-11-26 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="cmrcday">26</span>
		<p class="block-title">The Complete Micro-ring Course 26th November 2019 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>November 26th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Complete Micro-ring course at our Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>



<?php if (new DateTime() < new DateTime("2020-01-01 00:00:00")): ?>
	<br />
	<h3>December 2019</h3>
	<br />
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2019-12-16 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="cmrcday">16</span>
		<p class="block-title">The Complete Micro-ring Course 16th December 2019 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>December 16th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Complete Micro-ring course at our Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>



<?php if (new DateTime() < new DateTime("2020-02-01 00:00:00")): ?>
	<br />
	<h3>January 2020</h3>
	<br />
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2020-01-13 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="cmrcday">13</span>
		<p class="block-title">The Complete Micro-ring Course 13th January 2019 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>January 13th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Complete Micro-ring course at our Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>



<?php if (new DateTime() < new DateTime("2020-03-01 00:00:00")): ?>
	<br />
	<h3>Feruary 2020</h3>
	<br />
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2020-02-11 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="cmrcday">11</span>
		<p class="block-title">The Complete Micro-ring Course 11th February 2020 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>11th February 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Complete Micro-ring course at our Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2020-04-01 00:00:00")): ?>
	<br />
	<h3>March 2020</h3>
	<br />
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2020-03-09 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="cmrcday">09</span>
		<p class="block-title">The Complete Micro-ring Course 9th March 2020 London</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>9th March 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Complete Micro-ring course at our Training Academy in London. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<div class="uteclocation">
					<p>Location: Marylebone, London, W1H 8AQ, UK</p>
					<a href="http://maps.google.com/maps?f=q&hl=en&&saddr=George%20Street,%20Marylebone,%20London,%20W1H%208AQ" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>




<?php if (new DateTime() < new DateTime("2020-05-01 00:00:00")): ?>
	<br />
	<h3>April 2020</h3>
	<br />
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2020-04-07 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="cmrcday">07</span>
		<p class="block-title">The Complete Micro-ring Course 7th April 2020 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>April 7th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Complete Micro-ring course at our Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2020-06-01 00:00:00")): ?>
	<br />
	<h3>May 2020</h3>
	<br />
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2020-05-04 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="cmrcday">04</span>
		<p class="block-title">The Complete Micro-ring Course 4th May 2020 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>May 4th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Complete Micro-ring course at our Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2020-07-01 00:00:00")): ?>
	<br />
	<h3>June 2020</h3>
	<br />
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2020-06-02 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="cmrcday">02</span>
		<p class="block-title">The Complete Micro-ring Course 2nd June 2020 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>June 2nd 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Complete Micro-ring course at our Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2020-06-29 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="cmrcday">29</span>
		<p class="block-title">The Complete Micro-ring Course 29th June 2020 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>June 29th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Complete Micro-ring course at our Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2020-06-29 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="cmrcday">29</span>
		<p class="block-title">The Complete Micro-ring Course 29th June 2020 London</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>29th June 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Complete Micro-ring course at our Training Academy in London. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<div class="uteclocation">
					<p>Location: Marylebone, London, W1H 8AQ, UK</p>
					<a href="http://maps.google.com/maps?f=q&hl=en&&saddr=George%20Street,%20Marylebone,%20London,%20W1H%208AQ" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>



<?php if (new DateTime() < new DateTime("2020-08-01 00:00:00")): ?>
	<br />
	<h3>July 2020</h3>
	<br />
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2020-07-28 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="cmrcday">28</span>
		<p class="block-title">The Complete Micro-ring Course 28th July 2020 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>July 28th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Complete Micro-ring course at our Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2020-09-01 00:00:00")): ?>
	<br />
	<h3>August 2020</h3>
	<br />
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2020-08-24 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="cmrcday">24</span>
		<p class="block-title">The Complete Micro-ring Course 24th August 2020 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>August 24th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Complete Micro-ring course at our Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2020-10-01 00:00:00")): ?>
	<br />
	<h3>September 2020</h3>
	<br />
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2020-09-22 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="cmrcday">22</span>
		<p class="block-title">The Complete Micro-ring Course 22nd September 2020 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>September 22nd 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Complete Micro-ring course at our Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2020-11-01 00:00:00")): ?>
	<br />
	<h3>October 2020</h3>
	<br />
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2020-10-19 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="cmrcday">19</span>
		<p class="block-title">The Complete Micro-ring Course 19th October 2020 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>October 19th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Complete Micro-ring course at our Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>

<br /><br />
<button type="button" title="Go Back" class="button btn-cart" onclick="goBack()"><span><span>Go Back</span></span></button>

<script>
function goBack() {
    window.history.back();
}
</script>