<?php
/**
 * CMS view template
 *

 */
?>



<?php if (new DateTime() < new DateTime("2019-03-01 00:00:00")): ?>
	<br />
	<h3>February 2019</h3>
	<br />
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2019-02-18 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="cmrcday">18</span>
		<p class="block-title">The Creative Mix 2 Course 18th February 2019 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Feb 18th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Creative Mix 2 course at our Training Academy in Manchester. Price for the full day course is £649.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>





<?php if (new DateTime() < new DateTime("2019-04-01 00:00:00")): ?>
	<br />
	<h3>March 2019</h3>
	<br />
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2019-03-11 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="cmrcday">11</span>
		<p class="block-title">The Creative Mix 2 Course 11th March 2019 London</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Mar 11th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Creative Mix 2 course at our Training Academy in London. Price for the full day course is £649.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<div class="uteclocation">
					<p>Location: Marylebone, London, W1H 8AQ, UK</p>
					<a href="http://maps.google.com/maps?f=q&hl=en&&saddr=George%20Street,%20Marylebone,%20London,%20W1H%208AQ" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2019-03-25 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="cmrcday">25</span>
		<p class="block-title">The Creative Mix 2 Course 25th March 2019 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Mar 25th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Creative Mix 2 course at our Training Academy in Manchester. Price for the full day course is £649.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2019-06-01 00:00:00")): ?>
	<br />
	<h3>May 2019</h3>
	<br />
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2019-05-13 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="cmrcday">13</span>
		<p class="block-title">The Creative Mix 2 Course 13th May 2019 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>May 13th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Creative Mix 2 course at our Training Academy in Manchester. Price for the full day course is £649.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2019-07-01 00:00:00")): ?>
	<br />
	<h3>June 2019</h3>
	<br />
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2019-06-24 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="cmrcday">24</span>
		<p class="block-title">The Creative Mix 2 Course 24th June 2019 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>June 24th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Creative Mix 2 course at our Training Academy in Manchester. Price for the full day course is £649.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>



<?php if (new DateTime() < new DateTime("2019-08-01 00:00:00")): ?>
	<br />
	<h3>July 2019</h3>
	<br />
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2019-07-01 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="cmrcday">01</span>
		<p class="block-title">The Creative Mix 2 Course 1st July 2019 London</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Jul 1st 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Creative Mix 2 course at our Training Academy in London. Price for the full day course is £649.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<div class="uteclocation">
					<p>Location: Marylebone, London, W1H 8AQ, UK</p>
					<a href="http://maps.google.com/maps?f=q&hl=en&&saddr=George%20Street,%20Marylebone,%20London,%20W1H%208AQ" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2019-09-01 00:00:00")): ?>
	<br />
	<h3>August 2019</h3>
	<br />
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2019-08-06 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="cmrcday">06</span>
		<p class="block-title">The Creative Mix 2 Course 6th August 2019 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>August 6th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Creative Mix 2 course at our Training Academy in Manchester. Price for the full day course is £649.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2019-10-01 00:00:00")): ?>
	<br />
	<h3>September 2019</h3>
	<br />
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2019-09-16 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="cmrcday">16</span>
		<p class="block-title">The Creative Mix 2 Course 16th September 2019 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>September 16th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Creative Mix 2 course at our Training Academy in Manchester. Price for the full day course is £649.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>



<?php if (new DateTime() < new DateTime("2019-11-01 00:00:00")): ?>
	<br />
	<h3>October 2019</h3>
	<br />
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2019-10-14 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="cmrcday">14</span>
		<p class="block-title">The Creative Mix 2 Course 14th October 2019 London</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Oct 14th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Creative Mix 2 course at our Training Academy in London. Price for the full day course is £649.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<div class="uteclocation">
					<p>Location: Marylebone, London, W1H 8AQ, UK</p>
					<a href="http://maps.google.com/maps?f=q&hl=en&&saddr=George%20Street,%20Marylebone,%20London,%20W1H%208AQ" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2019-10-28 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="cmrcday">28</span>
		<p class="block-title">The Creative Mix 2 Course 28th October 2019 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>October 28th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Creative Mix 2 course at our Training Academy in Manchester. Price for the full day course is £649.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2019-12-01 00:00:00")): ?>
	<br />
	<h3>November 2019</h3>
	<br />
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2019-11-04 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="cmrcday">04</span>
		<p class="block-title">The Creative Mix 2 Course 4th November 2019 London</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Nov 4th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Creative Mix 2 course at our Training Academy in London. Price for the full day course is £649.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<div class="uteclocation">
					<p>Location: Marylebone, London, W1H 8AQ, UK</p>
					<a href="http://maps.google.com/maps?f=q&hl=en&&saddr=George%20Street,%20Marylebone,%20London,%20W1H%208AQ" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2019-11-11 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="cmrcday">11</span>
		<p class="block-title">The Creative Mix 2 Course 11th November 2019 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>November 11th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Creative Mix 2 course at our Training Academy in Manchester. Price for the full day course is £649.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>



<?php if (new DateTime() < new DateTime("2020-01-01 00:00:00")): ?>
	<br />
	<h3>December 2019</h3>
	<br />
<?php endif; ?>




<?php if (new DateTime() < new DateTime("2019-12-09 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="cmrcday">09</span>
		<p class="block-title">The Creative Mix 2 Course 9th December 2019 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>December 9th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Creative Mix 2 course at our Training Academy in Manchester. Price for the full day course is £649.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>





<?php if (new DateTime() < new DateTime("2020-02-01 00:00:00")): ?>
	<br />
	<h3>January 2020</h3>
	<br />
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2020-01-27 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="cmrcday">27</span>
		<p class="block-title">The Creative Mix 2 Course 27th January 2020 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>January 27th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Creative Mix 2 course at our Training Academy in Manchester. Price for the full day course is £649.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2020-03-01 00:00:00")): ?>
	<br />
	<h3>February 2020</h3>
	<br />
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2020-02-10 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="cmrcday">10</span>
		<p class="block-title">The Creative Mix 2 Course 10th February 2020 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>February 10th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Creative Mix 2 course at our Training Academy in Manchester. Price for the full day course is £649.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2020-02-24 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="cmrcday">24</span>
		<p class="block-title">The Creative Mix 2 Course 24th February 2020 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>February 24th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Creative Mix 2 course at our Training Academy in Manchester. Price for the full day course is £649.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>



<?php if (new DateTime() < new DateTime("2020-04-01 00:00:00")): ?>
	<br />
	<h3>March 2020</h3>
	<br />
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2020-03-23 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="cmrcday">23</span>
		<p class="block-title">The Creative Mix 2 Course 23rd March 2020 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>March 23rd 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Creative Mix 2 course at our Training Academy in Manchester. Price for the full day course is £649.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>




<?php if (new DateTime() < new DateTime("2020-05-01 00:00:00")): ?>
	<br />
	<h3>April 2020</h3>
	<br />
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2020-04-06 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="cmrcday">06</span>
		<p class="block-title">The Creative Mix 2 Course 6th April London</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>April 6th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Creative Mix 2 course at our Training Academy in London. Price for the full day course is £649.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<div class="uteclocation">
					<p>Location: Marylebone, London, W1H 8AQ, UK</p>
					<a href="http://maps.google.com/maps?f=q&hl=en&&saddr=George%20Street,%20Marylebone,%20London,%20W1H%208AQ" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2020-04-20 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="cmrcday">20</span>
		<p class="block-title">The Creative Mix 2 Course 20th April 2020 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>April 20th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Creative Mix 2 course at our Training Academy in Manchester. Price for the full day course is £649.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2020-06-01 00:00:00")): ?>
	<br />
	<h3>May 2020</h3>
	<br />
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2020-05-18 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="cmrcday">18</span>
		<p class="block-title">The Creative Mix 2 Course 18th May 2020 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>May 18th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Creative Mix 2 course at our Training Academy in Manchester. Price for the full day course is £649.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2020-07-01 00:00:00")): ?>
	<br />
	<h3>June 2020</h3>
	<br />
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2020-06-15 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="cmrcday">15</span>
		<p class="block-title">The Creative Mix 2 Course 15th June 2020 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>June 15th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Creative Mix 2 course at our Training Academy in Manchester. Price for the full day course is £649.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2020-08-01 00:00:00")): ?>
	<br />
	<h3>July 2020</h3>
	<br />
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2020-07-13 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="cmrcday">13</span>
		<p class="block-title">The Creative Mix 2 Course 13th July 2020 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>July 13th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Creative Mix 2 course at our Training Academy in Manchester. Price for the full day course is £649.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2020-07-20 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="cmrcday">20</span>
		<p class="block-title">The Creative Mix 2 Course 20th July London</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>July 20th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Creative Mix 2 course at our Training Academy in London. Price for the full day course is £649.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<div class="uteclocation">
					<p>Location: Marylebone, London, W1H 8AQ, UK</p>
					<a href="http://maps.google.com/maps?f=q&hl=en&&saddr=George%20Street,%20Marylebone,%20London,%20W1H%208AQ" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2020-09-01 00:00:00")): ?>
	<br />
	<h3>August 2020</h3>
	<br />
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2020-08-10 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="cmrcday">10</span>
		<p class="block-title">The Creative Mix 2 Course 10th August 2020 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>August 10th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Creative Mix 2 course at our Training Academy in Manchester. Price for the full day course is £649.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2020-10-01 00:00:00")): ?>
	<br />
	<h3>September 2020</h3>
	<br />
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2020-09-07 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="cmrcday">07</span>
		<p class="block-title">The Creative Mix 2 Course 7th September 2020 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>September 7th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Creative Mix 2 course at our Training Academy in Manchester. Price for the full day course is £649.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2020-11-01 00:00:00")): ?>
	<br />
	<h3>October 2020</h3>
	<br />
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2020-10-05 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="cmrcday">05</span>
		<p class="block-title">The Creative Mix 2 Course 5th October 2020 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>October 5th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Creative Mix 2 course at our Training Academy in Manchester. Price for the full day course is £649.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>

<br /><br />
<button type="button" title="Go Back" class="button btn-cart" onclick="goBack()"><span><span>Go Back</span></span></button>

<script>
function goBack() {
    window.history.back();
}
</script>