<?php
/**
 * CMS view template
 *

 */
?>
<?php if (new DateTime() < new DateTime("2017-10-01 00:00:00")): ?>
	<br />
	<h3>September 2017</h3>
	<br />
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2017-09-12 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="pmrcday">12</span>
		<p class="block-title">Pre-bonded and Micro-ring Course 12th Septmeber 2017 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Sep 12th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Pre-bonded and Micro-ring Course at new Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2017-11-01 00:00:00")): ?>
	<br />
	<h3>October 2017</h3>
	<br />
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2017-10-03 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="pmrcday">03</span>
		<p class="block-title">Pre-bonded and Micro-ring Course 3rd October 2017 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Oct 03rd 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Pre-bonded and Micro-ring Course at new Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2017-10-03 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="pmrcday">24</span>
		<p class="block-title">Pre-bonded and Micro-ring Course 24th October 2017 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Oct 24th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Pre-bonded and Micro-ring Course at new Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2017-12-01 00:00:00")): ?>
	<br />
	<h3>November 2017</h3>
	<br />
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2017-11-14 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="pmrcday">14</span>
		<p class="block-title">Pre-bonded and Micro-ring Course 14th October 2017 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Nov 14th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Pre-bonded and Micro-ring Course at new Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2018-01-01 00:00:00")): ?>
	<br />
	<h3>December 2017</h3>
	<br />
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2017-12-05 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="pmrcday">05</span>
		<p class="block-title">Pre-bonded and Micro-ring Course 05th December 2017 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Dec 05th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Pre-bonded and Micro-ring Course at new Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2018-02-01 00:00:00")): ?>
	<br />
	<h3>January 2018</h3>
	<br />
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2018-02-09 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="pmrcday">09</span>
		<p class="block-title">Pre-bonded and Micro-ring Course 9th January Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Jan 9th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Pre-bonded and Micro-ring Course at new Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2018-02-29 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="pmrcday">29</span>
		<p class="block-title">Pre-bonded and Micro-ring Course 29th January Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Jan 29th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Pre-bonded and Micro-ring Course at new Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2018-03-01 00:00:00")): ?>
	<br />
	<h3>February 2018</h3>
	<br />
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2018-02-20 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="pmrcday">20</span>
		<p class="block-title">Pre-bonded and Micro-ring Course 20th February Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Feb 20th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Pre-bonded and Micro-ring Course at new Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2018-04-01 00:00:00")): ?>
	<br />
	<h3>March 2018</h3>
	<br />
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2018-03-12 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="pmrcday">12</span>
		<p class="block-title">Pre-bonded and Micro-ring Course 12th March Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Mar 12th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Pre-bonded and Micro-ring Course at new Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2018-05-01 00:00:00")): ?>
	<br />
	<h3>April 2018</h3>
	<br />
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2018-04-02 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="pmrcday">02</span>
		<p class="block-title">Pre-bonded and Micro-ring Course 2nd April Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Apr 2nd 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Pre-bonded and Micro-ring Course at new Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2018-04-23 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="pmrcday">23</span>
		<p class="block-title">Pre-bonded and Micro-ring Course 23rd April Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Apr 23rd 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Pre-bonded and Micro-ring Course at new Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2018-06-01 00:00:00")): ?>
	<br />
	<h3>May 2018</h3>
	<br />
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2018-05-15 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="pmrcday">15</span>
		<p class="block-title">Pre-bonded and Micro-ring Course 15th May Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>May 15th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Pre-bonded and Micro-ring Course at new Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2018-07-01 00:00:00")): ?>
	<br />
	<h3>June 2018</h3>
	<br />
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2018-06-04 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="pmrcday">04</span>
		<p class="block-title">Pre-bonded and Micro-ring Course 4th June Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Jun 4th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Pre-bonded and Micro-ring Course at new Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2018-06-25 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="pmrcday">25</span>
		<p class="block-title">Pre-bonded and Micro-ring Course 25th June Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Jun 25th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Pre-bonded and Micro-ring Course at new Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2018-08-01 00:00:00")): ?>
	<br />
	<h3>July 2018</h3>
	<br />
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2018-07-16 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="pmrcday">16</span>
		<p class="block-title">Pre-bonded and Micro-ring Course 16th July Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Jul 16th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Pre-bonded and Micro-ring Course at new Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2018-09-01 00:00:00")): ?>
	<br />
	<h3>August 2018</h3>
	<br />
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2018-08-07 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="pmrcday">07</span>
		<p class="block-title">Pre-bonded and Micro-ring Course 7th August Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Aug 7th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Pre-bonded and Micro-ring Course at new Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2018-10-01 00:00:00")): ?>
	<br />
	<h3>September 2018</h3>
	<br />
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2018-09-03 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="pmrcday">03</span>
		<p class="block-title">Pre-bonded and Micro-ring Course 3rd September Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Sep 3rd 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Pre-bonded and Micro-ring Course at new Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2018-09-24 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="pmrcday">24</span>
		<p class="block-title">Pre-bonded and Micro-ring Course 24th September Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Sep 24th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Pre-bonded and Micro-ring Course at new Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2018-11-01 00:00:00")): ?>
	<br />
	<h3>October 2018</h3>
	<br />
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2018-10-15 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="pmrcday">15</span>
		<p class="block-title">Pre-bonded and Micro-ring Course 15th October Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Oct 15th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Pre-bonded and Micro-ring Course at new Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2018-12-01 00:00:00")): ?>
	<br />
	<h3>November 2018</h3>
	<br />
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2018-11-12 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="pmrcday">12</span>
		<p class="block-title">** CANCELLED ** Pre-bonded and Micro-ring Course 12th November Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Nov 12th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>** CANCELLED ** The Pre-bonded and Micro-ring Course at new Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2018-11-26 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="pmrcday">26</span>
		<p class="block-title">Pre-bonded and Micro-ring Course 26th November Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Nov 26th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Pre-bonded and Micro-ring Course at new Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2019-01-01 00:00:00")): ?>
	<br />
	<h3>December 2018</h3>
	<br />
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2018-12-10 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="pmrcday">10</span>
		<p class="block-title">Pre-bonded and Micro-ring Course 10th December Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Dec 10th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Pre-bonded and Micro-ring Course at new Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2019-02-01 00:00:00")): ?>
	<br />
	<h3>January 2019</h3>
	<br />
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2019-01-29 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="pmrcday">29</span>
		<p class="block-title">Pre-bonded and Micro-ring Course 29th January Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Jan 29th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Pre-bonded and Micro-ring Course at new Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2019-03-01 00:00:00")): ?>
	<br />
	<h3>February 2019</h3>
	<br />
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2019-02-19 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="pmrcday">19</span>
		<p class="block-title">Pre-bonded and Micro-ring Course 19th February Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Feb 19th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Pre-bonded and Micro-ring Course at new Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2019-04-01 00:00:00")): ?>
	<br />
	<h3>March 2019</h3>
	<br />
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2019-03-11 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="pmrcday">11</span>
		<p class="block-title">Pre-bonded and Micro-ring Course 11th March Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Mar 11th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Pre-bonded and Micro-ring Course at new Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>



<?php if (new DateTime() < new DateTime("2019-05-01 00:00:00")): ?>
	<br />
	<h3>April 2019</h3>
	<br />
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2019-04-01 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="pmrcday">01</span>
		<p class="block-title">Pre-bonded and Micro-ring Course 1st April Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Apr 1st 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Pre-bonded and Micro-ring Course at new Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2019-04-23 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="pmrcday">23</span>
		<p class="block-title">Pre-bonded and Micro-ring Course 23rd April Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Apr 23rd 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Pre-bonded and Micro-ring Course at new Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>



<?php if (new DateTime() < new DateTime("2019-06-01 00:00:00")): ?>
	<br />
	<h3>May 2019</h3>
	<br />
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2019-05-14 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="pmrcday">14</span>
		<p class="block-title">Pre-bonded and Micro-ring Course 14th May Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>May 14th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Pre-bonded and Micro-ring Course at new Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2019-07-01 00:00:00")): ?>
	<br />
	<h3>June 2019</h3>
	<br />
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2019-06-04 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="pmrcday">04</span>
		<p class="block-title">Pre-bonded and Micro-ring Course 4th June Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>June 4th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Pre-bonded and Micro-ring Course at new Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2019-06-25 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="pmrcday">25</span>
		<p class="block-title">Pre-bonded and Micro-ring Course 25th June Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>June 25th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Pre-bonded and Micro-ring Course at new Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>



<?php if (new DateTime() < new DateTime("2019-08-01 00:00:00")): ?>
	<br />
	<h3>July 2019</h3>
	<br />
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2019-07-15 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="pmrcday">15</span>
		<p class="block-title">Pre-bonded and Micro-ring Course 15th July Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>July 15th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Pre-bonded and Micro-ring Course at new Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>



<?php if (new DateTime() < new DateTime("2019-09-01 00:00:00")): ?>
	<br />
	<h3>August 2019</h3>
	<br />
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2019-08-05 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="pmrcday">05</span>
		<p class="block-title">Pre-bonded and Micro-ring Course 5th August Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>August 5th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Pre-bonded and Micro-ring Course at new Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2019-08-27 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="pmrcday">27</span>
		<p class="block-title">Pre-bonded and Micro-ring Course 27th August Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>August 27th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Pre-bonded and Micro-ring Course at new Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2019-10-01 00:00:00")): ?>
	<br />
	<h3>September 2019</h3>
	<br />
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2019-09-17 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="pmrcday">17</span>
		<p class="block-title">Pre-bonded and Micro-ring Course 17th September Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>September 17th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Pre-bonded and Micro-ring Course at new Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>



<?php if (new DateTime() < new DateTime("2019-11-01 00:00:00")): ?>
	<br />
	<h3>October 2019</h3>
	<br />
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2019-10-07 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="pmrcday">07</span>
		<p class="block-title">Pre-bonded and Micro-ring Course 7th October Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>October 7th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Pre-bonded and Micro-ring Course at new Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2019-10-29 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="pmrcday">29</span>
		<p class="block-title">Pre-bonded and Micro-ring Course 29th October Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>October 29th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Pre-bonded and Micro-ring Course at new Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>



<?php if (new DateTime() < new DateTime("2019-12-01 00:00:00")): ?>
	<br />
	<h3>November 2019</h3>
	<br />
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2019-11-18 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="pmrcday">18</span>
		<p class="block-title">Pre-bonded and Micro-ring Course 18th November Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>November 18th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Pre-bonded and Micro-ring Course at new Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2020-01-01 00:00:00")): ?>
	<br />
	<h3>December 2019</h3>
	<br />
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2019-12-10 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="pmrcday">10</span>
		<p class="block-title">Pre-bonded and Micro-ring Course 10th December Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>December 10th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Pre-bonded and Micro-ring Course at new Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>



<?php if (new DateTime() < new DateTime("2020-02-01 00:00:00")): ?>
	<br />
	<h3>January 2020</h3>
	<br />
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2020-01-14 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="pmrcday">14</span>
		<p class="block-title">Pre-bonded and Micro-ring Course 14th January Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>January 14th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Pre-bonded and Micro-ring Course at new Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>



<?php if (new DateTime() < new DateTime("2020-03-01 00:00:00")): ?>
	<br />
	<h3>February 2020</h3>
	<br />
<?php endif; ?>





<?php if (new DateTime() < new DateTime("2020-04-01 00:00:00")): ?>
	<br />
	<h3>March 2020</h3>
	<br />
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2020-03-10 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="pmrcday">10</span>
		<p class="block-title">Pre-bonded and Micro-ring Course 10th March Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>March 10th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Pre-bonded and Micro-ring Course at new Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>




<?php if (new DateTime() < new DateTime("2020-05-01 00:00:00")): ?>
	<br />
	<h3>April 2020</h3>
	<br />
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2020-04-06 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="pmrcday">06</span>
		<p class="block-title">Pre-bonded and Micro-ring Course 6th April Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>April 6th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Pre-bonded and Micro-ring Course at new Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>



<?php if (new DateTime() < new DateTime("2020-06-01 00:00:00")): ?>
	<br />
	<h3>May 2020</h3>
	<br />
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2020-05-05 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="pmrcday">05</span>
		<p class="block-title">Pre-bonded and Micro-ring Course 5th May Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>May 5th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Pre-bonded and Micro-ring Course at new Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2020-07-01 00:00:00")): ?>
	<br />
	<h3>June 2020</h3>
	<br />
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2020-06-01 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="pmrcday">01</span>
		<p class="block-title">Pre-bonded and Micro-ring Course 1st June Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>June 1st 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Pre-bonded and Micro-ring Course at new Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2020-06-30 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="pmrcday">30</span>
		<p class="block-title">Pre-bonded and Micro-ring Course 30th June Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>June 30th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Pre-bonded and Micro-ring Course at new Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2020-08-01 00:00:00")): ?>
	<br />
	<h3>July 2020</h3>
	<br />
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2020-07-27 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="pmrcday">27</span>
		<p class="block-title">Pre-bonded and Micro-ring Course 27th July Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>July 27th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Pre-bonded and Micro-ring Course at new Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2020-09-01 00:00:00")): ?>
	<br />
	<h3>August 2020</h3>
	<br />
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2020-08-25 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="pmrcday">25</span>
		<p class="block-title">Pre-bonded and Micro-ring Course 25th August Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>August 25th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Pre-bonded and Micro-ring Course at new Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2020-10-01 00:00:00")): ?>
	<br />
	<h3>September 2020</h3>
	<br />
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2020-09-21 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="pmrcday">21</span>
		<p class="block-title">Pre-bonded and Micro-ring Course 21th September Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>September 21th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Pre-bonded and Micro-ring Course at new Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2020-11-01 00:00:00")): ?>
	<br />
	<h3>October 2020</h3>
	<br />
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2020-10-20 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="pmrcday">20</span>
		<p class="block-title">Pre-bonded and Micro-ring Course 20th October Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>October 20th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Pre-bonded and Micro-ring Course at new Training Academy in Manchester. Price for the full day course is £549.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>


<br /><br />
<button type="button" title="Go Back" class="button btn-cart" onclick="goBack()"><span><span>Go Back</span></span></button>

<script>
function goBack() {
    window.history.back();
}
</script>


