<?php
/**
 * CMS view template
 *

 */
?>
<?php if (new DateTime() < new DateTime("2017-10-01 00:00:00")): ?>
	<br />
	<h3>September 2017</h3>
	<br />
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2017-09-18 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="utecday">18</span>
		<p class="block-title">The Ultimate Tape Course 18th September 2017 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Sep 18th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Ultimate Tape Course at new Training Academy in Manchester. Price for the full day course is £499.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2017-09-18 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="utecday">18</span>
		<p class="block-title">The Ultimate Tape Course 18th September 2017 London</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Sep 18th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Ultimate Tape Course at new Training Academy in London. Price for the full day course is £499.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-london.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Chelsea, London, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Real Hair, 6 Cale Street Chelsea" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2017-11-01 00:00:00")): ?>
	<br />
	<h3>October 2017</h3>
	<br />
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2017-10-09 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="utecday">09</span>
		<p class="block-title">The Ultimate Tape Course 9th October 2017 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Oct 09th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Ultimate Tape Course at new Training Academy in Manchester. Price for the full day course is £499.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2017-10-30 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="utecday">30</span>
		<p class="block-title">The Ultimate Tape Course 30th October 2017 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Oct 30th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Ultimate Tape Course at new Training Academy in Manchester. Price for the full day course is £499.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2017-10-30 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="utecday">30</span>
		<p class="block-title">The Ultimate Tape Course 30th October London</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Oct 30th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Ultimate Tape Course at new Training Academy in London. Price for the full day course is £499.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-london.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Chelsea, London, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Real Hair, 6 Cale Street Chelsea" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>



<?php if (new DateTime() < new DateTime("2017-12-01 00:00:00")): ?>
	<br />
	<h3>November 2017</h3>
	<br />
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2017-10-20 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="utecday">20</span>
		<p class="block-title">The Ultimate Tape Course 20th November 2017 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Nov 20th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Ultimate Tape Course at new Training Academy in Manchester. Price for the full day course is £499.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.	</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2018-01-01 00:00:00")): ?>
	<br />
	<h3>December 2017</h3>
	<br />
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2017-12-11 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="utecday">11</span>
		<p class="block-title">The Ultimate Tape Course 11th December 2017 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Dec 11th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Ultimate Tape Course at new Training Academy in Manchester. Price for the full day course is £499.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.	</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2018-02-01 00:00:00")): ?>
	<br />
	<h3>January 2018</h3>
	<br />
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2018-01-15 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="utecday">15</span>
		<p class="block-title">The Ultimate Tape Course 15th January 2018 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Jan 15th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Ultimate Tape Course at new Training Academy in Manchester. Price for the full day course is £499.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.	</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2018-01-15 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="utecday">15</span>
		<p class="block-title">The Ultimate Tape Course 15th January 2018 London</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Jan 15th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Ultimate Tape Course at new Training Academy in London. Price for the full day course is £499.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-london.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Chelsea, London, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Real Hair, 6 Cale Street Chelsea" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2018-03-01 00:00:00")): ?>
	<br />
	<h3>February 2018</h3>
	<br />
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2018-02-06 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="utecday">06</span>
		<p class="block-title">The Ultimate Tape Course 6th February  2018 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Feb 6th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Ultimate Tape Course at new Training Academy in Manchester. Price for the full day course is £499.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.	</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2018-02-26 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="utecday">26</span>
		<p class="block-title">The Ultimate Tape Course 26th February  2018 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Feb 26th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Ultimate Tape Course at new Training Academy in Manchester. Price for the full day course is £499.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.	</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2018-04-01 00:00:00")): ?>
	<br />
	<h3>March 2018</h3>
	<br />
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2018-03-12 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="utecday">12</span>
		<p class="block-title">The Ultimate Tape Course 12th March 2018 London</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Mar 12th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Ultimate Tape Course at new Training Academy in London. Price for the full day course is £499.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-london.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Chelsea, London, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Real Hair, 6 Cale Street Chelsea" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2018-02-19 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="utecday">19</span>
		<p class="block-title">The Ultimate Tape Course 19th March  2018 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Mar 19th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Ultimate Tape Course at new Training Academy in Manchester. Price for the full day course is £499.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.	</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2018-05-01 00:00:00")): ?>
	<br />
	<h3>April 2018</h3>
	<br />
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2018-02-06 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="utecday">06</span>
		<p class="block-title">The Ultimate Tape Course 6th February  2018 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Feb 6th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Ultimate Tape Course at new Training Academy in Manchester. Price for the full day course is £499.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.	</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2018-06-01 00:00:00")): ?>
	<br />
	<h3>May 2018</h3>
	<br />
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2018-05-01 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="utecday">01</span>
		<p class="block-title">The Ultimate Tape Course 1st May 2018 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>May 1st 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Ultimate Tape Course at new Training Academy in Manchester. Price for the full day course is £499.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.	</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2018-05-07 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="utecday">07</span>
		<p class="block-title">The Ultimate Tape Course 7th May 2018 London</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>May 7th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Ultimate Tape Course at new Training Academy in London. Price for the full day course is £499.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-london.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Chelsea, London, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Real Hair, 6 Cale Street Chelsea" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2018-05-21 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="utecday">21</span>
		<p class="block-title">The Ultimate Tape Course 21st May 2018 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>May 21st 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Ultimate Tape Course at new Training Academy in Manchester. Price for the full day course is £499.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.	</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2018-07-01 00:00:00")): ?>
	<br />
	<h3>June 2018</h3>
	<br />
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2018-06-11 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="utecday">11</span>
		<p class="block-title">The Ultimate Tape Course 11th June 2018 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Jun 11th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Ultimate Tape Course at new Training Academy in Manchester. Price for the full day course is £499.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.	</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2018-08-01 00:00:00")): ?>
	<br />
	<h3>July 2018</h3>
	<br />
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2018-07-02 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="utecday">02</span>
		<p class="block-title">The Ultimate Tape Course 2nd July 2018 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Jul 2nd 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Ultimate Tape Course at new Training Academy in Manchester. Price for the full day course is £499.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.	</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2018-07-09 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="utecday">09</span>
		<p class="block-title">The Ultimate Tape Course 9th July 2018 London</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Jul 9th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Ultimate Tape Course at new Training Academy in London. Price for the full day course is £499.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-london.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Chelsea, London, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Real Hair, 6 Cale Street Chelsea" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2018-07-17 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="utecday">17</span>
		<p class="block-title">The Ultimate Tape Course 17th July 2018 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Jul 17th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Ultimate Tape Course at new Training Academy in Manchester. Price for the full day course is £499.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.	</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2018-09-01 00:00:00")): ?>
	<br />
	<h3>August 2018</h3>
	<br />
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2018-08-13 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="utecday">13</span>
		<p class="block-title">The Ultimate Tape Course 13th August 2018 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Aug 13th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Ultimate Tape Course at new Training Academy in Manchester. Price for the full day course is £499.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.	</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2018-10-01 00:00:00")): ?>
	<br />
	<h3>September 2018</h3>
	<br />
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2018-09-10 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="utecday">10</span>
		<p class="block-title">The Ultimate Tape Course 10th September 2018 London</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Sep 10th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Ultimate Tape Course at new Training Academy in London. Price for the full day course is £499.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-london.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Chelsea, London, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Real Hair, 6 Cale Street Chelsea" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2018-09-11 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="utecday">11</span>
		<p class="block-title">The Ultimate Tape Course 11th September 2018 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Sep 11th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Ultimate Tape Course at new Training Academy in Manchester. Price for the full day course is £499.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.	</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2018-11-01 00:00:00")): ?>
	<br />
	<h3>October 2018</h3>
	<br />
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2018-10-01 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="utecday">01</span>
		<p class="block-title">The Ultimate Tape Course 1st October 2018 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Oct 1st 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Ultimate Tape Course at new Training Academy in Manchester. Price for the full day course is £499.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.	</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2018-10-23 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="utecday">23</span>
		<p class="block-title">The Ultimate Tape Course 23rd October 2018 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Oct 23rd 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Ultimate Tape Course at new Training Academy in Manchester. Price for the full day course is £499.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.	</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2018-12-01 00:00:00")): ?>
	<br />
	<h3>November 2018</h3>
	<br />
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2018-11-05 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="utecday">05</span>
		<p class="block-title">The Ultimate Tape Course 5th November 2018 London</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Nov 5th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Ultimate Tape Course at new Training Academy in London. Price for the full day course is £499.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-london.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Chelsea, London, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Real Hair, 6 Cale Street Chelsea" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2018-11-20 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="utecday">20</span>
		<p class="block-title">The Ultimate Tape Course 20th November 2018 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Nov 20th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Ultimate Tape Course at new Training Academy in Manchester. Price for the full day course is £499.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.	</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2019-01-01 00:00:00")): ?>
	<br />
	<h3>December 2018</h3>
	<br />
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2018-12-03 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="utecday">03</span>
		<p class="block-title">The Ultimate Tape Course 3rd December 2018 London</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Dec 3rd 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Ultimate Tape Course at new Training Academy in London. Price for the full day course is £499.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-london.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Chelsea, London, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Real Hair, 6 Cale Street Chelsea" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2018-12-18 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="utecday">18</span>
		<p class="block-title">The Ultimate Tape Course 18th December 2018 London</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Dec 18th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Ultimate Tape Course at new Training Academy in London. Price for the full day course is £499.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-london.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Chelsea, London, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Real Hair, 6 Cale Street Chelsea" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>



<?php if (new DateTime() < new DateTime("2019-02-01 00:00:00")): ?>
	<br />
	<h3>January 2019</h3>
	<br />
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2019-01-07 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="utecday">07</span>
		<p class="block-title">The Ultimate Tape Course 7th January 2019 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Jan 7th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Ultimate Tape Course at new Training Academy in Manchester. Price for the full day course is £499.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.	</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2019-01-14 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="utecday">14</span>
		<p class="block-title">The Ultimate Tape Course 14th January 2019 London</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Jan 14th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Ultimate Tape Course at new Training Academy in London. Price for the full day course is £499.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-london.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Marylebone, London, UK</p>
					<a href="http://maps.google.com/maps?f=q&hl=en&&saddr=George%20Street,%20Marylebone,%20London,%20W1H%208AQ" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2019-01-21 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="utecday">21</span>
		<p class="block-title">The Ultimate Tape Course 21st January 2019 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Jan 21st 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Ultimate Tape Course at new Training Academy in Manchester. Price for the full day course is £499.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.	</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2019-03-01 00:00:00")): ?>
	<br />
	<h3>February 2019</h3>
	<br />
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2019-02-11 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="utecday">11</span>
		<p class="block-title">The Ultimate Tape Course 11th February 2019 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Feb 11th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Ultimate Tape Course at new Training Academy in Manchester. Price for the full day course is £499.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.	</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2019-04-01 00:00:00")): ?>
	<br />
	<h3>March 2019</h3>
	<br />
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2019-03-04 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="utecday">04</span>
		<p class="block-title">The Ultimate Tape Course 4th March 2019 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Mar 4th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Ultimate Tape Course at new Training Academy in Manchester. Price for the full day course is £499.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.	</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2019-03-26 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="utecday">26</span>
		<p class="block-title">The Ultimate Tape Course 26th March 2019 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Mar 26th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Ultimate Tape Course at new Training Academy in Manchester. Price for the full day course is £499.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.	</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2019-05-01 00:00:00")): ?>
	<br />
	<h3>April 2019</h3>
	<br />
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2019-04-08 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="utecday">08</span>
		<p class="block-title">The Ultimate Tape Course 8th April 2019 London</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Apr 8th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Ultimate Tape Course at new Training Academy in London. Price for the full day course is £499.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-london.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Marylebone, London, UK</p>
					<a href="http://maps.google.com/maps?f=q&hl=en&&saddr=George%20Street,%20Marylebone,%20London,%20W1H%208AQ" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2019-04-15 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="utecday">15</span>
		<p class="block-title">The Ultimate Tape Course 15th March 2019 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Apr 15th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Ultimate Tape Course at new Training Academy in Manchester. Price for the full day course is £499.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.	</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2019-06-01 00:00:00")): ?>
	<br />
	<h3>May 2019</h3>
	<br />
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2019-05-07 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="utecday">07</span>
		<p class="block-title">The Ultimate Tape Course 7th May 2019 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>May 7th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Ultimate Tape Course at new Training Academy in Manchester. Price for the full day course is £499.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.	</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>





<?php if (new DateTime() < new DateTime("2019-07-01 00:00:00")): ?>
	<br />
	<h3>June 2019</h3>
	<br />
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2019-06-03 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="utecday">03</span>
		<p class="block-title">The Ultimate Tape Course 3rd June 2019 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>June 3rd 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Ultimate Tape Course at new Training Academy in Manchester. Price for the full day course is £499.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.	</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2019-06-17 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="utecday">17</span>
		<p class="block-title">The Ultimate Tape Course 17th June 2019 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>June 17th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Ultimate Tape Course at new Training Academy in Manchester. Price for the full day course is £499.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.	</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>





<?php if (new DateTime() < new DateTime("2019-08-01 00:00:00")): ?>
	<br />
	<h3>July 2019</h3>
	<br />
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2019-07-08 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="utecday">08</span>
		<p class="block-title">The Ultimate Tape Course 8th July 2019 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>July 8th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Ultimate Tape Course at new Training Academy in Manchester. Price for the full day course is £499.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.	</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2019-07-29 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="utecday">29</span>
		<p class="block-title">The Ultimate Tape Course 29th July 2019 London</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>July 29th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Ultimate Tape Course at new Training Academy in London. Price for the full day course is £499.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-london.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Marylebone, London, UK</p>
					<a href="http://maps.google.com/maps?f=q&hl=en&&saddr=George%20Street,%20Marylebone,%20London,%20W1H%208AQ" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2019-09-01 00:00:00")): ?>
	<br />
	<h3>August 2019</h3>
	<br />
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2019-07-19 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="utecday">19</span>
		<p class="block-title">The Ultimate Tape Course 19th August 2019 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Augusst 19th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Ultimate Tape Course at new Training Academy in Manchester. Price for the full day course is £499.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.	</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2019-10-01 00:00:00")): ?>
	<br />
	<h3>September 2019</h3>
	<br />
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2019-09-09 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="utecday">09</span>
		<p class="block-title">The Ultimate Tape Course 9th September 2019 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>September 9th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Ultimate Tape Course at new Training Academy in Manchester. Price for the full day course is £499.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.	</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2019-09-30 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="utecday">30</span>
		<p class="block-title">The Ultimate Tape Course 30th September 2019 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>September 930th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Ultimate Tape Course at new Training Academy in Manchester. Price for the full day course is £499.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.	</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>



<?php if (new DateTime() < new DateTime("2019-11-01 00:00:00")): ?>
	<br />
	<h3>October 2019</h3>
	<br />
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2019-10-21 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="utecday">21</span>
		<p class="block-title">The Ultimate Tape Course 21st October 2019 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Octber 21st 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Ultimate Tape Course at new Training Academy in Manchester. Price for the full day course is £499.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.	</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2019-12-01 00:00:00")): ?>
	<br />
	<h3>November 2019</h3>
	<br />
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2019-11-11 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="utecday">11</span>
		<p class="block-title">The Ultimate Tape Course 11th November 2019 London</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Nov 11th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Ultimate Tape Course at new Training Academy in London. Price for the full day course is £499.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-london.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Marylebone, London, UK</p>
					<a href="http://maps.google.com/maps?f=q&hl=en&&saddr=George%20Street,%20Marylebone,%20London,%20W1H%208AQ" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>






<?php if (new DateTime() < new DateTime("2020-01-01 00:00:00")): ?>
	<br />
	<h3>December 2019</h3>
	<br />
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2019-11-11 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="utecday">02</span>
		<p class="block-title">The Ultimate Tape Course 2nd December 2019 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>December 2nd  9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Ultimate Tape Course at new Training Academy in Manchester. Price for the full day course is £499.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.	</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>



<?php if (new DateTime() < new DateTime("2020-02-01 00:00:00")): ?>
	<br />
	<h3>January 2020</h3>
	<br />
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2020-01-06 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="utecday">06</span>
		<p class="block-title">The Ultimate Tape Course 6th January 2020 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>January 6th  9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Ultimate Tape Course at new Training Academy in Manchester. Price for the full day course is £499.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.	</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2020-01-13 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="utecday">13</span>
		<p class="block-title">The Ultimate Tape Course 13th January 2020 London</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>January 13th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Ultimate Tape Course at new Training Academy in London. Price for the full day course is £499.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-london.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Marylebone, London, UK</p>
					<a href="http://maps.google.com/maps?f=q&hl=en&&saddr=George%20Street,%20Marylebone,%20London,%20W1H%208AQ" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2020-03-01 00:00:00")): ?>
	<br />
	<h3>February 2020</h3>
	<br />
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2020-02-03 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="utecday">03</span>
		<p class="block-title">The Ultimate Tape Course 3rd February 2020 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>February 3rd  9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Ultimate Tape Course at new Training Academy in Manchester. Price for the full day course is £499.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.	</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>



<?php if (new DateTime() < new DateTime("2020-04-01 00:00:00")): ?>
	<br />
	<h3>March 2020</h3>
	<br />
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2020-03-02 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="utecday">02</span>
		<p class="block-title">The Ultimate Tape Course 2nd March 2020 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>March 2nd  9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Ultimate Tape Course at new Training Academy in Manchester. Price for the full day course is £499.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.	</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2020-03-30 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="utecday">30</span>
		<p class="block-title">The Ultimate Tape Course 30th March 2020 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>March 30th  9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Ultimate Tape Course at new Training Academy in Manchester. Price for the full day course is £499.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.	</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>




<?php if (new DateTime() < new DateTime("2020-05-01 00:00:00")): ?>
	<br />
	<h3>April 2020</h3>
	<br />
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2020-04-27 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="utecday">27</span>
		<p class="block-title">The Ultimate Tape Course 27th April 2020 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>April 27th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Ultimate Tape Course at new Training Academy in Manchester. Price for the full day course is £499.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.	</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2020-06-01 00:00:00")): ?>
	<br />
	<h3>May 2020</h3>
	<br />
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2020-05-04 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="utecday">04</span>
		<p class="block-title">The Ultimate Tape Course 4th May 2020 London</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>May 4th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Ultimate Tape Course at new Training Academy in London. Price for the full day course is £499.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-london.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Marylebone, London, UK</p>
					<a href="http://maps.google.com/maps?f=q&hl=en&&saddr=George%20Street,%20Marylebone,%20London,%20W1H%208AQ" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2020-05-26 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="utecday">26</span>
		<p class="block-title">The Ultimate Tape Course 26th May 2020 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>May 26th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Ultimate Tape Course at new Training Academy in Manchester. Price for the full day course is £499.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.	</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2020-07-01 00:00:00")): ?>
	<br />
	<h3>June 2020</h3>
	<br />
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2020-06-22 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="utecday">22</span>
		<p class="block-title">The Ultimate Tape Course 22nd June 2020 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>June 22nd 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Ultimate Tape Course at new Training Academy in Manchester. Price for the full day course is £499.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.	</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>



<?php if (new DateTime() < new DateTime("2020-08-01 00:00:00")): ?>
	<br />
	<h3>July 2020</h3>
	<br />
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2020-07-20 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="utecday">20</span>
		<p class="block-title">The Ultimate Tape Course 20th July 2020 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>July 20th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Ultimate Tape Course at new Training Academy in Manchester. Price for the full day course is £499.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.	</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2020-09-01 00:00:00")): ?>
	<br />
	<h3>August 2020</h3>
	<br />
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2020-08-17 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="utecday">17</span>
		<p class="block-title">The Ultimate Tape Course 17th August 2020 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>August 17th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Ultimate Tape Course at new Training Academy in Manchester. Price for the full day course is £499.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.	</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2020-10-01 00:00:00")): ?>
	<br />
	<h3>September 2020</h3>
	<br />
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2020-09-14 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="utecday">14</span>
		<p class="block-title">The Ultimate Tape Course 14th September 2020 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>September 14th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Ultimate Tape Course at new Training Academy in Manchester. Price for the full day course is £499.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.	</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2020-11-01 00:00:00")): ?>
	<br />
	<h3>October 2020</h3>
	<br />
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2020-10-12 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="utecday">12</span>
		<p class="block-title">The Ultimate Tape Course 12th October 2020 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>October 12th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>The Ultimate Tape Course at new Training Academy in Manchester. Price for the full day course is £499.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.	</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>

<br /><br />
<button type="button" title="Go Back" class="button btn-cart" onclick="goBack()"><span><span>Go Back</span></span></button>

<script>
function goBack() {
    window.history.back();
}
</script>