<?php
/**
 * CMS view template
 *

 */
?>
<?php if (new DateTime() < new DateTime("2017-10-01 00:00:00")): ?>
	<br />
	<h3>September 2017</h3>
	<br />
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2017-09-11 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="uwwcday">11</span>
		<p class="block-title">The Ultimate Weft &amp; Weave Course 11th September 2017 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Sep 11th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>Wefting Course at new Training Academy in Manchester. Price for the full day course is £449.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2017-11-01 00:00:00")): ?>
	<br />
	<h3>October 2017</h3>
	<br />
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2017-10-02 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="uwwcday">02</span>
		<p class="block-title">The Ultimate Weft &amp; Weave Course 2nd October 2017 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Oct 02nd 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>Wefting Course at new Training Academy in Manchester. Price for the full day course is £449.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2017-10-23 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="uwwcday">23</span>
		<p class="block-title">The Ultimate Weft &amp; Weave Course 23rd October 2017 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Oct 23rd 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>Wefting Course at new Training Academy in Manchester. Price for the full day course is £449.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2017-12-01 00:00:00")): ?>
	<br />
	<h3>November 2017</h3>
	<br />
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2017-11-13 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="uwwcday">13</span>
		<p class="block-title">The Ultimate Weft &amp; Weave Course 13th November 2017 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Nov 13th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>Wefting Course at new Training Academy in Manchester. Price for the full day course is £449.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2018-01-01 00:00:00")): ?>
	<br />
	<h3>December 2017</h3>
	<br />
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2017-12-04 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="uwwcday">04</span>
		<p class="block-title">The Ultimate Weft &amp; Weave Course 4th December 2017 Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Dec 04th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>Wefting Course at new Training Academy in Manchester. Price for the full day course is £449.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2018-02-01 00:00:00")): ?>
	<br />
	<h3>January 2018</h3>
	<br />
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2018-01-22 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="uwwcday">22</span>
		<p class="block-title">The Ultimate Weft &amp; Weave Course 22nd January Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Jan 22nd 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>Wefting Course at new Training Academy in Manchester. Price for the full day course is £449.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2018-03-01 00:00:00")): ?>
	<br />
	<h3>February 2018</h3>
	<br />
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2018-02-12 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="uwwcday">12</span>
		<p class="block-title">The Ultimate Weft &amp; Weave Course 12th Febraury Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Feb 12th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>Wefting Course at new Training Academy in Manchester. Price for the full day course is £449.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2018-04-01 00:00:00")): ?>
	<br />
	<h3>March 2018</h3>
	<br />
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2018-03-05 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="uwwcday">05</span>
		<p class="block-title">The Ultimate Weft &amp; Weave Course 5th March Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Mar 5th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>Wefting Course at new Training Academy in Manchester. Price for the full day course is £449.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2018-03-26 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="uwwcday">26</span>
		<p class="block-title">The Ultimate Weft &amp; Weave Course 26th March Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Mar 26th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>Wefting Course at new Training Academy in Manchester. Price for the full day course is £449.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2018-05-01 00:00:00")): ?>
	<br />
	<h3>April 2018</h3>
	<br />
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2018-04-17 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="uwwcday">17</span>
		<p class="block-title">The Ultimate Weft &amp; Weave Course 17th April Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Apr 17th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>Wefting Course at new Training Academy in Manchester. Price for the full day course is £449.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2018-06-01 00:00:00")): ?>
	<br />
	<h3>May 2018</h3>
	<br />
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2018-05-07 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="uwwcday">07</span>
		<p class="block-title">The Ultimate Weft &amp; Weave Course 7th May Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>May 7th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>Wefting Course at new Training Academy in Manchester. Price for the full day course is £449.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2018-05-28 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="uwwcday">28</span>
		<p class="block-title">The Ultimate Weft &amp; Weave Course 28th May Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>May 28th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>Wefting Course at new Training Academy in Manchester. Price for the full day course is £449.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2018-07-01 00:00:00")): ?>
	<br />
	<h3>June 2018</h3>
	<br />
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2018-06-18 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="uwwcday">18</span>
		<p class="block-title">The Ultimate Weft &amp; Weave Course 18th June Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Jun 18th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>Wefting Course at new Training Academy in Manchester. Price for the full day course is £449.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2018-08-01 00:00:00")): ?>
	<br />
	<h3>July 2018</h3>
	<br />
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2018-07-10 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="uwwcday">10</span>
		<p class="block-title">The Ultimate Weft &amp; Weave Course 10th July Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Jul 10th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>Wefting Course at new Training Academy in Manchester. Price for the full day course is £449.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2018-07-30 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="uwwcday">30</span>
		<p class="block-title">The Ultimate Weft &amp; Weave Course 30th July Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Jul 30th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>Wefting Course at new Training Academy in Manchester. Price for the full day course is £449.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>



<?php if (new DateTime() < new DateTime("2018-09-01 00:00:00")): ?>
	<br />
	<h3>August 2018</h3>
	<br />
<?php endif; ?>



<?php if (new DateTime() < new DateTime("2018-10-01 00:00:00")): ?>
	<br />
	<h3>September 2018</h3>
	<br />
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2018-09-17 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="uwwcday">17</span>
		<p class="block-title">The Ultimate Weft &amp; Weave Course 17th September Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Sep 17th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>Wefting Course at new Training Academy in Manchester. Price for the full day course is £449.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2018-11-01 00:00:00")): ?>
	<br />
	<h3>October 2018</h3>
	<br />
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2018-10-29 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="uwwcday">29</span>
		<p class="block-title">The Ultimate Weft &amp; Weave Course 29th October Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Oct 29th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>Wefting Course at new Training Academy in Manchester. Price for the full day course is £449.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>



<?php if (new DateTime() < new DateTime("2018-12-01 00:00:00")): ?>
	<br />
	<h3>November 2018</h3>
	<br />
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2018-11-27 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="uwwcday">27</span>
		<p class="block-title">The Ultimate Weft &amp; Weave Course 27th November Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Nov 27th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>Wefting Course at new Training Academy in Manchester. Price for the full day course is £449.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2019-03-01 00:00:00")): ?>
	<br />
	<h3>February 2019</h3>
	<br />
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2019-02-26 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="uwwcday">26</span>
		<p class="block-title">The Ultimate Weft &amp; Weave Course 26th February Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Feb 26th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>Wefting Course at new Training Academy in Manchester. Price for the full day course is £449.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2019-06-01 00:00:00")): ?>
	<br />
	<h3>May 2019</h3>
	<br />
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2019-05-28 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="uwwcday">28</span>
		<p class="block-title">The Ultimate Weft &amp; Weave Course 28th May Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>May 28th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>Wefting Course at new Training Academy in Manchester. Price for the full day course is £449.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2019-09-01 00:00:00")): ?>
	<br />
	<h3>August 2019</h3>
	<br />
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2019-08-20 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="uwwcday">20</span>
		<p class="block-title">The Ultimate Weft &amp; Weave Course 20th August Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>Aug 20th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>Wefting Course at new Training Academy in Manchester. Price for the full day course is £449.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>



<?php if (new DateTime() < new DateTime("2019-12-01 00:00:00")): ?>
	<br />
	<h3>November 2019</h3>
	<br />
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2019-11-19 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="uwwcday">19</span>
		<p class="block-title">The Ultimate Weft &amp; Weave Course 19th November Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>November 19th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>Wefting Course at new Training Academy in Manchester. Price for the full day course is £449.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>



<?php if (new DateTime() < new DateTime("2020-03-01 00:00:00")): ?>
	<br />
	<h3>February 2020</h3>
	<br />
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2020-02-17 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="uwwcday">17</span>
		<p class="block-title">The Ultimate Weft &amp; Weave Course 17th February Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>February 17th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>Wefting Course at new Training Academy in Manchester. Price for the full day course is £449.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2020-04-01 00:00:00")): ?>
	<br />
	<h3>March 2020</h3>
	<br />
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2020-05-01 00:00:00")): ?>
	<br />
	<h3>April 2020</h3>
	<br />
<?php endif; ?>


<?php if (new DateTime() < new DateTime("2020-06-01 00:00:00")): ?>
	<br />
	<h3>May 2020</h3>
	<br />
<?php endif; ?>

<?php if (new DateTime() < new DateTime("2020-05-19 09:30:00")): ?>
	<div class="collapsible coursedates"><span class="opener">&nbsp;</span>	
	<span class="uwwcday">19</span>
		<p class="block-title">The Ultimate Weft &amp; Weave Course 19th May Manchester</p>
			<div class="feature-wrapper block-content" style="display: none;">
				<!--TIME-->
				<div class="utectime utectimeico">
					<p><strong>Event Times</strong></p>
					<p>May 19th 9:30 am - 5:00 pm</p>
				</div>
				<!--DETAILS-->
				<div class="uteceventico">
					<p><strong>Event Details</strong></p>
					<p>Wefting Course at new Training Academy in Manchester. Price for the full day course is £449.99. Reserve your place now, limited spaces available. Requires a 50% deposit which is non-refundable.</p>
				</div>
				<!--MAP-->
				<img class="utecmapico" src="/media/bwt2017/beauty-works-training-hq.jpg" alt="" title="">
				<!--DIRECTION-->
				<div class="uteclocation">
					<p>Location: Beauty Works HQ Manchester, UK</p>
					<a href="http://maps.google.com/maps?f=q&amp;hl=en&amp;&amp;saddr=Unit D3 Commercial Ave, Stanley Green Business Park, SK86 QH" target="_blank"> Get Directions</a>
				</div>
				<!--CONTACT-->
				<div class="uteccontact"><a href="mailto:sales@beautyworks.co.uk">sales@beautyworks.co.uk </a> |
				0843 289 5198 | 0161 485 3602</div>
			</div>
				
	</div>
<?php endif; ?>



<br /><br />
<button type="button" title="Go Back" class="button btn-cart" onclick="goBack()"><span><span>Go Back</span></span></button>

<script>
function goBack() {
    window.history.back();
}
</script>